name: Android CI/CD

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Hamein working-directory specify karni padegi taake commands sahi folder me chalein
    - name: Grant Execute Permission for Gradle
      working-directory: YTS-application-
      run: chmod +x gradlew

    - name: Build Debug APK
      working-directory: YTS-application-
      run: ./gradlew assembleDebug --no-daemon
      
